choices/urls.py
from django.urls import path
from . import views

app_name = 'choices'

urlpatterns = [
    path('<int:question_pk>/answer_delete/<int:answer_pk>/', views.answer_delete, name="answer_delete"),
    path('<int:question_pk>/question_delete/', views.question_delete, name="question_delete"),
    path('new/', views.new, name="new"),
    path('<int:question_pk>/vote/', views.vote, name="vote"),
    path('', views.index, name="index"),
]

either95/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('choices/', include('choices.urls')),
    path('admin/', admin.site.urls),
]

choices/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=50)
    selection1 = models.CharField(max_length=50)
    selection2 = models.CharField(max_length=50)
    
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick = models.IntegerField()
    comment = models.TextField()

choices/views.py
from django.shortcuts import render, redirect
from .models import Question, Answer
import requests
import os

# Create your views here.
def index(request):
    if request.method == "POST":
        title = request.POST.get('title')
        selection1 = request.POST.get('selection1')
        selection2 = request.POST.get('selection2')
        question = Question(title=title, selection1=selection1, selection2=selection2)
        question.save()
        return redirect('choices:index')
    else:
        questions = Question.objects.all()
        context = {
            'questions' : questions,
            }
        return render(request, 'choices/index.html', context)
        
def vote(request, question_pk):
    if request.method == "POST":
        print(request.POST.get('pick'))
        pick = int(request.POST.get('pick'))
        
        comment = request.POST.get('comment')
        answer = Answer(pick=pick, comment=comment, question_id=question_pk)
        answer.save()
        return redirect('choices:vote', question_pk=question_pk)
    else:
        question = Question.objects.get(pk=question_pk)
        GIPHY_API = 'b0GIlipiKq6qMKrOdSVxAAKRgjYK1Otn'
        url1 = f'http://api.giphy.com/v1/gifs/search?api_key={GIPHY_API}&q={question.selection1}&limit=1&lang=ko'
        url2 = f'http://api.giphy.com/v1/gifs/search?api_key={GIPHY_API}&q={question.selection2}&limit=1&lang=ko'
        data1 = requests.get(url1).json()
        data2 = requests.get(url2).json()
        image1 = data1.get('data')[0].get('images').get('original').get('url')
        image2 = data2.get('data')[0].get('images').get('original').get('url')
        answers = question.answer_set.all()

        if len(answers) !=0:
            pick1 = question.answer_set.filter(pick=0).count()
            pick1_per = str(round(pick1/len(answers)*100))+'%'
            pick2 = question.answer_set.filter(pick=1).count()
            pick2_per = str(round(pick2/len(answers)*100))+'%'
        else: 
            pick1_per ='0'
            pick2_per ='0'
        
        context = {
            'question' : question,
            'answers' : answers,
            'pick1_per': pick1_per,
            'pick2_per' : pick2_per,
            'image1' : image1,
            'image2' : image2,
            }
        return render(request, 'choices/vote.html', context)
        
def new(request):
    return render(request, 'choices/new.html')
    
def question_delete(request, question_pk):
    question = Question.objects.get(pk=question_pk)
    question.delete()
    return redirect('choices:index')
    
def answer_delete(request, question_pk, answer_pk):
    answer = Answer.objects.get(pk=answer_pk)
    answer.delete()
    return redirect('choices:vote', question_pk)
    

    

choices/templates/choices/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Your Choices -{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<style>
    body {
        height : 2000px;
        background-color : pink;
    }
</style>
</head>
<body>
    <div class="container">
    <a href="{% url 'choices:index' %}"><h1>Your Choices</h1></a>
    <hr>
   {% block body %} 
   
   {% endblock %} 
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

choices/templates/choices/index.html
{% extends 'choices/base.html' %}
{% block title %}
LIST
{% endblock %}
{% block body %}

<div class="list-group">
  <a href="#" class="list-group-item list-group-item-action active">
    당신의 ~~~~~ 선택은 ~~~~~~~?
  </a>
  <a href="{% url 'choices:new' %}">[선택지 추가]</a>
  <hr>
  {% for question in questions %}
  <div class="text-center">
  <a href="{% url 'choices:vote' question.pk %}" class="list-group-item list-group-item-action"><b>{{ question.title }}</b></a>
  </div>
  <a href="{% url 'choices:question_delete' question.pk %}">[삭제]</a>
{% endfor %}
</div>
{% endblock %}

choices/templates/choices/new.html
{% extends 'choices/base.html' %}
{% block title %}
NEW
{% endblock %}
{% block body %}

<form action="{% url 'choices:index' %}" method="POST">
    {% csrf_token %}
    TITLE : <input type="text" name="title"/>
    선택지1 : <input type="text" name="selection1"/>
    선택지2 : <input type="text" name="selection2"/>
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

choices/templates/choices/vote.html
{% extends 'choices/base.html' %} {% block title %} VOTE {% endblock %} {% block body %}
<h3 class='text-center'>* {{ question.title }} *</h3>


  <div class='d-flex justify-content-between my-3'>
    <div>
      <img src="{{ image1 }}" height='300px' width='400px'><br>
    </div>
    <div class='d-flex align-self-center'>
      <img src="https://image.flaticon.com/icons/svg/753/753228.svg" height='100px' width='100px'><br>
    </div>
    <div>
      <img src="{{ image2 }}" height='300px' width='400px'><br>
    </div>
  </div>
  
  <form method="POST">
  {% csrf_token %}

  <div class = 'd-flex justify-content-center my-4'>
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
      <label class="btn btn-outline-primary btn-lg">
      <input type="radio" name="pick" value = '0'autocomplete="off" style='width:50%'> {{question.selection1 }}
      </label>
      <label class="btn btn-outline-warning btn-lg" >
      <input type="radio" name="pick" value = '1' autocomplete="off" style='width:50%'> {{question.selection2 }}
      </label>
    
    </div>

  </div>

  <label>댓글작성하기</label>
  <input class="form-control form-control-lg" name = 'comment'type="text" placeholder="의견을 달아주세요">
  <input class='btn btn-success my-2' type="submit" value="Submit" />
  
  
  
</form>
<br>
<div class="progress">
  <div class="progress-bar" role="progressbar" style="width: {{ pick1_per }}" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{ pick1_per }}</div>
  <div class="progress-bar bg-warning" role="progressbar" style="width: {{ pick2_per }}" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">{{ pick2_per }}</div>
</div>
<a href="{% url 'choices:index' %}">[back]</a>


<hr>
<p>{{ answers | length }}개의 댓글이 달렸습니다</p>
{% for answer in answers %}
{% if answer.pick == 0 %}

<marquee direction="right" scrollamount='500'>
  <span>
    <span class="badge badge-pill badge-primary">{{question.selection1}}</span>
    {{answer.comment    }}    </span>
    <a href="{% url 'choices:answer_delete' question.pk answer.pk %}" class="btn btn-secondary active btn-sm mx-2" role="button" aria-pressed="true">Delete</a>
    </marquee>


{% else %}
<marquee direction="left" scrollamount='500'>
  <span>
    <span class="badge badge-pill badge-warning">{{question.selection2}}</span>
    {{answer.comment    }}    </span>
    <a href="{% url 'choices:answer_delete' question.pk answer.pk %}" class="btn btn-secondary active btn-sm mx-2" role="button" aria-pressed="true">Delete</a>
    </marquee>
{% endif %}

<hr>
{% endfor %} 
{% endblock %}